In [27]:
import numpy as np

A = [[6,2,3,5],[4,6,2,6],[1,3,6,7],[3,6,3,8]]
Z = [[6,2,3,5],[4,6,2,6],[1,3,6,7],[3,6,3,8]]

B = np.triu(Z)
print(B)
print("\n")

C = np.tril(Z)
print(C)
print("\n")

D = np.triu(C)
print(D)

A == B

M = np.eye(0)
def est_diagonal(M):
    return True if (M == np.triu(np.tril(M))).all() else False

def est_triangulaire_sup(M):
    return True if (M == np.tril(M)).all() else False
print("\n")

def est_triangulaire_inf(M):
    return True if (M == np.triu(M)).all() else False # "True" et "False" sont déjà induits par le "return"
print("\n")


print(est_diagonal(M))

print(est_triangulaire_sup(M))

print(est_triangulaire_inf(M))


[[6 2 3 5]
 [0 6 2 6]
 [0 0 6 7]
 [0 0 0 8]]


[[6 0 0 0]
 [4 6 0 0]
 [1 3 6 0]
 [3 6 3 8]]


[[6 0 0 0]
 [0 6 0 0]
 [0 0 6 0]
 [0 0 0 8]]




True
True
True
