In [9]:
import numpy as np

A = np.random.rand(50, 50)                  # Matrice aléatoire de flottants
print(A)

count = np.count_nonzero(A <= 0.5)          # Compte le nombre de valeurs < à 0.5
print("\n")
print(count)

B = (A > 0.5).astype(int)                   # Remplace toutes les valeurs < à 0.5 par 0 et les autres par 1
print(B)
print("\n")

C = np.select (A <= 0.5, A)
np.ceil(C)

D = np.select (A > 0.5, A)
np.floor(D)

print(np.ceil(C))
print(np.floor(D))
print("\n")

D = np.where (A, A < 0.5, 0.1)
print(D)





[[0.72829961 0.96332757 0.12522036 ... 0.91763026 0.57236657 0.84431484]
 [0.70780932 0.15873237 0.99885123 ... 0.51156379 0.17767484 0.224648  ]
 [0.93457016 0.80233679 0.4047437  ... 0.11000861 0.88213993 0.60080366]
 ...
 [0.41783372 0.51950213 0.98448914 ... 0.82136141 0.36831199 0.17564671]
 [0.62509584 0.97719671 0.59536506 ... 0.2188249  0.1345408  0.80343412]
 [0.56401273 0.64910472 0.56778074 ... 0.2396491  0.27097546 0.08885917]]


1224
[[1 1 0 ... 1 1 1]
 [1 0 1 ... 1 0 0]
 [1 1 0 ... 0 1 1]
 ...
 [0 1 1 ... 1 0 0]
 [1 1 1 ... 0 0 1]
 [1 1 1 ... 0 0 0]]


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


[[0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 1. 1.]
 [0. 0. 1. ... 1. 0. 0.]
 ...
 [1. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. .